name = "std::documentation"
version = "0.47.2"
description = "Offline documentation HTML website"
repository = "https://github.com/uwe-app/documentation"
license = ["MIT", "Apache-2.0"]
keywords = ["Documentation"]
type = "library"
