name = "std::documentation"
version = "0.42.10"
description = "Offline documentation HTML website"
repository = "https://github.com/uwe-app/documentation"
type = "library"
keywords = ["Documentation"]
license = ["MIT", "Apache-2.0"]
